---
- hosts: localhost
  connection: local
  vars_files:
    - group_vars/vars.yml
  become: yes
  tasks:
    - name: Add public key to authorized_keys
      lineinfile:
        path: /home/vagrant/.ssh/authorized_keys
        line: "{{ jenkins_slave_public_key }}"
        create: yes
    - name: "Install java jre"
      yum:
        name: java-1.8.0-openjdk
        state: latest